import SwiftUI

struct AddWordView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var input = ""
    @State private var preview: ChineseWord?
    @State private var isGenerating = false
    @State private var errorMessage: String?

    var body: some View {
        NavigationStack {
            Form {
                Section("Chinese word") {
                    TextField("e.g. 加油", text: $input)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                }

                if let preview {
                    Section("Preview") {
                        VStack(alignment: .leading, spacing: 6) {
                            Text(preview.hanzi).font(.system(size: 34, weight: .bold))
                            Text(preview.pinyinDisplay).foregroundStyle(.pink)
                            Text(preview.englishShort).foregroundStyle(.secondary)
                            Label(
                                preview.source == .ai ? "Generated by AI" : "From dictionary",
                                systemImage: preview.source == .ai ? "sparkles" : "book"
                            )
                            .font(.caption2)
                            .foregroundStyle(.tertiary)
                        }
                    }
                }

                if let errorMessage {
                    Section {
                        Text(errorMessage).foregroundStyle(.red).font(.footnote)
                    }
                }

                Section {
                    Button {
                        Task { await lookup() }
                    } label: {
                        if isGenerating {
                            ProgressView()
                        } else {
                            Text("Look up")
                        }
                    }
                    .disabled(input.trimmingCharacters(in: .whitespaces).isEmpty || isGenerating)

                    if preview != nil {
                        Button("Save") { save() }
                            .fontWeight(.semibold)
                    }
                }
            }
            .navigationTitle("Add word")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
            }
        }
    }

    private func lookup() async {
        errorMessage = nil
        preview = nil
        isGenerating = true
        defer { isGenerating = false }

        let word = input.trimmingCharacters(in: .whitespacesAndNewlines)

        // 1. Try the free, offline dictionary first.
        if let found = DictionaryLookup.shared.lookup(word) {
            preview = found
            return
        }

        // 2. Fall back to AI generation.
        do {
            preview = try await AIWordGenerator.generate(for: word)
        } catch AIWordGenerator.GenerationError.missingAPIKey {
            errorMessage = "Not in the dictionary. Add an Anthropic API key in Settings to auto-generate new words."
        } catch {
            errorMessage = "Couldn't generate this word. Check your connection and API key."
        }
    }

    private func save() {
        guard let preview else { return }
        WordStore.add(preview)
        dismiss()
    }
}
